# 1. Install Maven on staging host
# 2. Install tomcat on production host
# 3. Build java app
# 4. Copy artefact to production server

---
- name: Install Maven
  hosts: staging
  become: yes

  tasks:
  - name: Ensure openJDK is present
    apt:
     name: default-jdk
     update_cache: yes
     state: present

  - name: Ensure maven is present
    apt:
     name: maven
     update_cache: yes
     state: present

- name: Install Tomcat
  hosts: production
  become: yes
  
  tasks:
  - name: Ensure tomcat is present
    apt:
     name: tomcat9
     update_cache: yes
     state: present

  - name: Ensure tomcat service is running
    service:
     name: tomcat9
     state: started

- name: Build java application
  hosts: staging
  become: yes

  tasks:
  - name: Get java application
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
     clone: yes
     dest: /tmp/boxfuse-sample-java-war-hello

  - name: Build procces java application
    shell: mvn package
    args:    
      chdir: /tmp/boxfuse-sample-java-war-hello

- name: Copy artefact to production server
  hosts: production
  become: yes

  tasks:

  - name: Fetch war file to master from staging
    run_once: yes
    shell: scp root@devops-instance-2:/tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war /var/lib/tomcat9/webapps/hello-1.0.war
     
     
     


    